test_config_runs:
  stage: test
  script:
    - python3 ./all_options.py # Generate config file
    - mkdir -p ~/.config # Just in case
    - make # Build nvim config
    - |
      output=$(nvim --headless -c 'qa' 2 2>&1 >/dev/null) # Dry run nvim
      if [ -n "$output" ]
      then
        echo "$output" >&2
        exit 1
      fi
