test_config_runs:
  stage: test
  before_script:
    - mkdir -p ~/.config # Just in case
    - rm -rf ~/.config/nvim
    - python3 -m venv venv
    - source venv/bin/activate
    - venv/bin/pip install pynvim
    - export NVIM_PYTHON3_HOST_PROG="$PWD/venv/bin/python"
  script:
    - python3 ./all_options.py # Generate config file
    - |
      output=$(make 2>&1 >/dev/null <<< $'\n') # Build nvim config
      if [ -n "$output" ]
      then
        echo "$output" >&2
        exit 1
      fi
