test_config_runs:
  stage: test
  script:
    - script -q -c 'make config' <<< 'Gklalalalalall'
    - make
    - |
      output=$(nvim --headless -c 'qa' 2 2>&1 >/dev/null)
      if [ -n "$output" ]
      then
        echo "$output" >&2
        exit 1
      fi
